# Generated by Django 5.0.4 on 2024-04-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
